project_id = "mclszzrjwhrhfqtonuiw"

[functions.generate-lead-magnets]
verify_jwt = false

[functions.fetch-google-doc]
verify_jwt = false

[functions.generate-project-name]
verify_jwt = false

[functions.generate-content]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.generate-pipeline]
verify_jwt = false

[functions.generate-pipeline-images]
verify_jwt = false
